# Generated by Django 4.0.4 on 2022-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_user_profile_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('mobile_number', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('age', models.IntegerField(default=0)),
                ('user_image', models.ImageField(default=None, upload_to='media/')),
                ('fee', models.IntegerField(default=0)),
                ('Qualification', models.TextField(blank=True)),
                ('Experience', models.IntegerField(default=0)),
            ],
        ),
    ]
